# Site settings
title: Bryan Fullam
email: bryanfullam@gmail.com
description: "Thinker // Developer // Student"



# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested